### ISSUE TITLE
[BE] UCI ODK Adapter - shift to CDAC service instead of UCI

### ISSUE THREAD

**Issue by choxx** [Samarth-HP/odk-uci-adapter#6]
Currently, we are using UCI for sending SMSes to users under the SMS module. We need to start consuming CDAC service instead because UCI has some internal issues causing instability in sending SMSes.

**Comment by choxx** [comment]
### Blocker items:
- [x] Need currently deployed CDAC service URL & Credentials
- [x] If the above is not available, then need help in debugging the deployed service on staging. 

Currently, the hosted service on staging is throwing exception:

![Image](https://user-images.githubusercontent.com/11666456/214241259-95998303-fc4c-4e84-8b0c-1788e752ee54.png)

@ChakshuGautam

**Comment by ChakshuGautam** [comment]
Hey, can you restart the service and try again? The domain is resolving on my laptop. Alternatively, can you ping the base URL from the droplet?

**Comment by choxx** [comment]
> Hey, can you restart the service and try again? The domain is resolving on my laptop. Alternatively, can you ping the base URL from the droplet?

No luck on restart. `ping msdgweb.mgov.gov.in` is not responding from CLI on server as well as my local machine.

**Comment by choxx** [comment]
_Update as on 24.01.2023:_ 
- [x] Code sided changes DONE; PR raised; 
- [x] Test cases
- [x] Final integration/deployment after fixing CDAC Service (https://github.com/Samarth-HP/CDAC-Service/pull/5)

**Comment by choxx** [comment]
Related **(production deployment blocker)** ticket: https://github.com/Samarth-HP/CDAC-Service/issues/6
